;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
c=cls
..=cd ..
cra=create-react-app
rni=react-native init
rnra=react-native run-android
ys=yarn start
yt=yarn test
gs=git status
gb=git branch -a
gpm=git pull --rebase origin master
gfp=git fetch --prune
gr=git reset HEAD~1
config=code D:\Daniyar\Programs\WebTools\cmder\config
web=cd d:\code
vid=cd d:\Daniyar\CS\
